### ISSUE TITLE
Only get 10 items

### ISSUE THREAD

**Issue by ivanmunozruiz** [marcreichel/igdb-laravel#1]
Hello, I am requesting for next releases games where first_release_date is > now, but I only get 10 objects, this is a limit? thanks!

**Comment by marcreichel** [comment]
Hi, 

10 is the default limit. Please refer to https://github.com/marcreichel/igdb-laravel/blob/master/readme.md#skip--take on how to change the limit accordingly to your current tier from IGDB.
