### ISSUE TITLE
How to recover the game id

### ISSUE THREAD

**Issue by Askancy** [marcreichel/igdb-laravel#12]
Doing the search by name I find it too risky to fail, just go by complex name and you are asked to break the system.
at the moment I get the game ID from the page source example:

`data-react-props="{"id":1274`

But is there no way to enter the url and get the game ID to get the API system started?

**Comment by marcreichel** [comment]
Well, one opportunity would be to search via the slug of the game. The slug is unique and the part of the URL. For example: https://www.igdb.com/games/fortnite
„fortnite“ is the slug so you could make a where clause with `Game::where('slug', 'fortnite')->first()`.
Hope this helps.
