### ISSUE TITLE
Empty Result everytime

### ISSUE THREAD

**Issue by hawkiq** [marcreichel/igdb-laravel#17]
Hello I don't know whats wrong I followed every step in Readme to install and use this package but I got empty results 

    public function index(){
        $games = Game::where('first_release_date', '>=', 1556661661000)->get();
        return $games;
    }

**Comment by paishin** [comment]
I have the same issue but only when I run the request from console. If I add it to a web route it seems to work ok.
@hawkiq, how are you calling your method?

**Comment by marcreichel** [comment]
The timestamp should be provided without milliseconds. Then it should work as expected.
Please excuse the late answer.
