### ISSUE TITLE
One question about cover

### ISSUE THREAD

**Issue by ivanmunozruiz** [marcreichel/igdb-laravel#2]
is it posibble to get a cover bigger? now If i get cover I get one thumbnail 90x90, thanks!

**Comment by marcreichel** [comment]
The thumbnail is the default size. The URL structure is https://images.igdb.com/igdb/image/upload/t_{size}/{hash}.jpg
You need to change the {size} parameter in the URL to get a bigger Cover.
The docs from IGDB list the available sizes.

**Comment by HDVinnie** [comment]
How does one do that exactly? I dont see anything in the config and when I do 

`<img src="{{ $meta->cover->url ?? 'https://via.placeholder.com/600x900' }}" class="movie-poster img-responsive hidden-xs">`

The image is tiny and pixelated. I want full-res.

**Comment by marcreichel** [comment]
Just replace `t_thumb` with `t_cover_big` of the cover url i.e. via `str_replace` or `preg_replace`

**Comment by arya-lunaris** [comment]
> Just replace `t_thumb` with `t_cover_big` of the cover url i.e. via `str_replace` or `preg_replace`

Found this comment and had to thank you, I spent ages trying to figure this out for a project!
