### ISSUE TITLE
Help with platform filter

### ISSUE THREAD

**Issue by jadersilvabr** [marcreichel/igdb-laravel#23]
Hello,

I did not found an example for my needs.

I would like to get a total games of Playstation 2 and a list of games.

1) I tryed get total with this  code, but platform is a relation and did not work:

`$platforms_games_total = Game::where('platforms', '28')->count();`

I'm receiving Null as return.

2) I tryed get a list of playstation 2 games, but this also did not work:

`$games = Game::where('platforms', '28')->get();`

Could you help me?

Best regards.

**Comment by scottcharlesworth** [comment]
@jadersilvabr the `count()` method is broken. I've done a pull request to fix it (#24).

The ID for "Playstation 2" is 8, not 28 (which doesn't exist).

The following returns results:
```php
$games = Game::where('platforms', 8)->get();
```

**Comment by jadersilvabr** [comment]
Hi @scottcharlesworth 

Sorry for my confusion with ID.

I did some tests now and I only getting 10 games (register) per request. 

I checked my `igdb.php` config file and is set to 500 `'per_page_limit' => 500,`.

There is another file to set limit?

If I use `$games = Game::all();` I get all games (500).

Could you help me?

Ps: The `count()` method working fine after fix #24.

Best regards.
