### ISSUE TITLE
Example of pagination

### ISSUE THREAD

**Issue by jadersilvabr** [marcreichel/igdb-laravel#25]
Hi,

Could you give me an example of pagination? I did not succeed in my tests.

When i try execute `Game::where('rating_count', '>=', 800)->with(['cover'])->Paginate(48);`

I got result like bellow:

![image](https://user-images.githubusercontent.com/58928002/98060219-d883b480-1e27-11eb-856a-b061e2b4d8d7.png)

And this didn't working.

Best regards.

**Comment by marcreichel** [comment]
Hi, you can use the `skip` and `take` methods to get a pagination. Calling `paginate` directly is not supported for now.

**Comment by jadersilvabr** [comment]
Ok, thank you.
