### ISSUE TITLE
Update composer.json for 5.8 release?

### ISSUE THREAD

**Issue by lofonic** [marcreichel/igdb-laravel#3]
Wondering if application compatibility includes 5.8 and if so can we get an update on the requirements to 5.7 and up?

**Comment by marcreichel** [comment]
Good Point. I Will definetely look into this!

**Comment by lofonic** [comment]
Cool, maybe as simple as making the composer requirement something like
`"laravel/framework": "5.*.*",`

And just making sure it doesn't step on the toes of any 5.8 changes:
https://laravel.com/docs/5.8/upgrade

**Comment by lofonic** [comment]
Ok I forked and tried removing the laravel requirement altogether it seems to work fine. Checking the 5.8 changes the only impact for this package appears to be with regards to caching which changes the amount to equal seconds instead of minutes however since you have a config folks can change the time in there easily enough.

**Comment by marcreichel** [comment]
Sounds great. Feel free to send me a PR.
But make sure to add the Laravel dependency again as this package would not work without it 😄

**Comment by lofonic** [comment]
Will do, I'll pull a fresh fork since there's like 6 commits of me trying different composer file tests.

**Comment by marcreichel** [comment]
Leaving this issue open until you send me the PR
