### ISSUE TITLE
Count total results?

### ISSUE THREAD

**Issue by benzgrant** [marcreichel/igdb-laravel#40]
Hi there,
is there a way to count total results from a query? Using `->count()` doesn't return the total number of results.

Thanks

**Comment by marcreichel** [comment]
@benzgrant Which version of `igdb-laravel` do you use and could you please provide the query/code you used?

Because with the latest version and the following example query the total count is returned just fine:

```php
dd(Game::select(['name', 'aggregated_rating_count'])->where('aggregated_rating_count', '>', 5)->count());

// 2624
```

**Comment by benzgrant** [comment]
I was going through the source code of this library to understand how `count()` works.

Calling `count()` when building the query works. Calling it after `get()` gives the size of the collection.

Thank you for the prompt response 😄

**Comment by marcreichel** [comment]
No worries 🙂 

I'm here to help 😄
