### ISSUE TITLE
title": "Syntax Error"

### ISSUE THREAD

**Issue by maxpayneovh** [marcreichel/igdb-laravel#63]
"title": "Syntax Error",
    "status": 400,
    "cause": "Expecting a STRING as input, surround your input wit (truncated...)
 {"userId":1,"exception":"[object] (Illuminate\\Http\\Client\\RequestException(code: 400): HTTP request returned status code 400:

those ids:
100983 
113389 
163758 

"title": "Internal server error",
    "status": 500,
    "type": "https://javalin.io/documentation#internalservere (truncated...)
 {"userId":1,"exception":"[object] (Illuminate\\Http\\Client\\RequestException(code: 500): HTTP request returned status code 500:
{

125764

**Comment by marcreichel** [comment]
Please provide more information on how to reproduce this error. What code resulted in this error?

**Comment by maxpayneovh** [comment]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Client/Response.php(275): Illuminate\\Http\\Client\\Response->toException()
#1 /var/www/html/vendor/marcreichel/igdb-laravel/src/Builder.php(1716): Illuminate\\Http\\Client\\Response->throw()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(391): MarcReichel\\IGDBLaravel\\Builder->MarcReichel\\IGDBLaravel\\{closure}()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(418): Illuminate\\Cache\\Repository->remember()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Cache\\CacheManager->__call()
#5 /var/www/html/vendor/marcreichel/igdb-laravel/src/Builder.php(1724): Illuminate\\Support\\Facades\\Facade::__callStatic()
#6 /var/www/html/vendor/marcreichel/igdb-laravel/src/Builder.php(1538): MarcReichel\\IGDBLaravel\\Builder->fetchApi()
#7 /var/www/html/app/Http/Controllers/TorrentController.php(206): MarcReichel\\IGDBLaravel\\Builder->get()

**Comment by marcreichel** [comment]
And what code did you run which returned this error? So for example:

```php
Game::where('name', 'Fortnite')->get();
```

The stack trace alone does not help.

**Comment by maxpayneovh** [comment]
we fixed it, it was on our end

**Comment by MadMikeyB** [comment]
> we fixed it, it was on our end

Hiya, how did you fix it? Having this issue now and I'm sure it's user error but cannot figure it out.
