### ISSUE TITLE
Only get official releases

### ISSUE THREAD

**Issue by kaiserkiwi** [marcreichel/igdb-laravel#67]
Hi there, 

I use this package for a few days now to fetch some games. But the IGDB ist pretty "dirty" as I think. They have many games that aren't actual games. If I search for "Pokémon" I get something like "Pokemon: Greg Version" which is a fangame. Is there any way to filter these titles and only get "real" games? I suppose not but before I make a huge denylist for IDs I just wanted to asks if this Wrapper has something in place to help me out.

Kind Regards,
Marco

**Comment by marcreichel** [comment]
Hi, thanks for opening this issue.

I'm afraid there is no elegant way of receiving this as IGDB makes no differentiation between those games. I think the closest you can get is by filtering out games of the indie category which should eliminate most of the games you do not want (I assume). But keep in mind there are some official titles out there which are considered as an “indie game” nevertheless.

But this may be the only way of achieving this without creating a blacklist of IDs.

In the end it all comes down to the data quality on IGDB though. When an indie game is not marked as an indie game on IGDB it would show up in your results nonetheless.
