### ISSUE TITLE
Extracting a list of available platforms

### ISSUE THREAD

**Issue by Askancy** [marcreichel/igdb-laravel#82]
Hi. Is there any way to explore a list of platforms that IGDB has?
I would need an example list: https://gist.github.com/ahmed-abdelazim/b533b443388baaafab3fc377e71e0109
but in json format so that I can import it more easily...

**Comment by marcreichel** [comment]
```php
use MarcReichel\IGDBLaravel\Models\Platform;

$platforms = Platform::all();
$json = json_encode($platforms);
```

This gives you a collection of all 200 platforms that currently exist on IGDB.
