### ISSUE TITLE
[Feature Request] Implement the new PopScore Endpoints

### ISSUE THREAD

**Issue by kaiserkiwi** [marcreichel/igdb-laravel#95]
The IGDB just announced a new set of endpoints to get data based on a games popularity. 

These endpoints are available now. 

See the announcement on the IGDB blog.
https://medium.com/igdb/introducing-igdb-popscore-your-ultimate-tool-for-tracking-gaming-trends-b8d9beacf16a

New endpoints:
- `https://api.igdb.com/v4/popularity_types`
- `https://api.igdb.com/v4/popularity_primitives`

There's also a way to combine these things. See use case 2 in the api docs: https://api-docs.igdb.com/#how-to-use-popularity-api

**Comment by marcreichel** [comment]
@kaiserkiwi Thanks for pointing this out! I will look into this the coming week 👍🏼

**Comment by marcreichel** [comment]
@kaiserkiwi I've implemented the new endpoints in v4.3.0 👍🏼 Feel free to update 🙂

Your mentioned combination of `PopularityType` and `PopularityPrimitive` is something you have to do in your app. That is not something I can do inside this package. Just like mentioned by IGDB themselves:

> To do that you would have to pull the values for each popularity type in your own system and then combine them accordingly.
> To pull the date you’ll need locally a data structure similar to the existing popularity primitive where it will have the attributes.

**Comment by kaiserkiwi** [comment]
Oh wow, that was fast. Thank you!

> Your mentioned combination of PopularityType and PopularityPrimitive is something you have to do in your app. That is not something I can do inside this package. Just like mentioned by IGDB themselves:

Ok, thank you for the mention. I'll figure it out 😊
